// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateRecord(ctx context.Context, arg *CreateRecordParams) (int64, error)
	// 获取商品当前owner
	GetObjOwner(ctx context.Context, objectid int32) (sql.NullString, error)
	// 根据id查找流转记录
	GetRecordById(ctx context.Context, id int32) (*CircRecord, error)
	// 根据流转实体id查找流转记录, 按流转顺序降序排列，最新的在第一个
	GetRecordByObjIdDesc(ctx context.Context, objectid int32) ([]*CircRecord, error)
	// 根据transId查找流转记录
	GetRecordByTransId(ctx context.Context, transid string) (*CircRecord, error)
	// 更新流转记录状态
	UpdateStatus(ctx context.Context, arg *UpdateStatusParams) error
}

var _ Querier = (*Queries)(nil)
