// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 未找到交易记录
func IsRecordNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Error_RECORD_NOT_FOUND.String() && e.Code == 404
}

// 未找到交易记录
func ErrorRecordNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, Error_RECORD_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 记录重复
func IsDuplicateErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Error_DUPLICATE_ERR.String() && e.Code == 400
}

// 记录重复
func ErrorDuplicateErr(format string, args ...interface{}) *errors.Error {
	return errors.New(400, Error_DUPLICATE_ERR.String(), fmt.Sprintf(format, args...))
}

// 已存在的交易
func IsTransAlreadyExist(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Error_TRANS_ALREADY_EXIST.String() && e.Code == 400
}

// 已存在的交易
func ErrorTransAlreadyExist(format string, args ...interface{}) *errors.Error {
	return errors.New(400, Error_TRANS_ALREADY_EXIST.String(), fmt.Sprintf(format, args...))
}
