// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: vtrace/v1/errors.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	// 不允许的操作
	Error_PERMISSION_DENIED Error = 0
	// 服务未上线
	Error_SERVICE_OFFLINE Error = 1
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "PERMISSION_DENIED",
		1: "SERVICE_OFFLINE",
	}
	Error_value = map[string]int32{
		"PERMISSION_DENIED": 0,
		"SERVICE_OFFLINE":   1,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_vtrace_v1_errors_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_vtrace_v1_errors_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_vtrace_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_vtrace_v1_errors_proto protoreflect.FileDescriptor

var file_vtrace_v1_errors_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76, 0x74, 0x72, 0x61, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x1a, 0x11, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x45, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x1b, 0x0a, 0x11, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45,
	0x4e, 0x49, 0x45, 0x44, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0x93, 0x03, 0x12, 0x19, 0x0a, 0x0f,
	0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45, 0x10,
	0x01, 0x1a, 0x04, 0xa8, 0x45, 0xf4, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x2e, 0x5a,
	0x2c, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x63, 0x69, 0x69, 0x70,
	0x2d, 0x69, 0x63, 0x70, 0x2f, 0x76, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vtrace_v1_errors_proto_rawDescOnce sync.Once
	file_vtrace_v1_errors_proto_rawDescData = file_vtrace_v1_errors_proto_rawDesc
)

func file_vtrace_v1_errors_proto_rawDescGZIP() []byte {
	file_vtrace_v1_errors_proto_rawDescOnce.Do(func() {
		file_vtrace_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_vtrace_v1_errors_proto_rawDescData)
	})
	return file_vtrace_v1_errors_proto_rawDescData
}

var file_vtrace_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vtrace_v1_errors_proto_goTypes = []interface{}{
	(Error)(0), // 0: vtrace.v1.Error
}
var file_vtrace_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vtrace_v1_errors_proto_init() }
func file_vtrace_v1_errors_proto_init() {
	if File_vtrace_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vtrace_v1_errors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtrace_v1_errors_proto_goTypes,
		DependencyIndexes: file_vtrace_v1_errors_proto_depIdxs,
		EnumInfos:         file_vtrace_v1_errors_proto_enumTypes,
	}.Build()
	File_vtrace_v1_errors_proto = out.File
	file_vtrace_v1_errors_proto_rawDesc = nil
	file_vtrace_v1_errors_proto_goTypes = nil
	file_vtrace_v1_errors_proto_depIdxs = nil
}
