// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: ca/v1/ca.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CAServiceClient is the client API for CAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CAServiceClient interface {
	GenCert(ctx context.Context, in *GenCertRequest, opts ...grpc.CallOption) (*GenCertResponse, error)
	GetCert(ctx context.Context, in *GetCertRequest, opts ...grpc.CallOption) (*GetCertResponse, error)
}

type cAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCAServiceClient(cc grpc.ClientConnInterface) CAServiceClient {
	return &cAServiceClient{cc}
}

func (c *cAServiceClient) GenCert(ctx context.Context, in *GenCertRequest, opts ...grpc.CallOption) (*GenCertResponse, error) {
	out := new(GenCertResponse)
	err := c.cc.Invoke(ctx, "/ca.v1.CAService/GenCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cAServiceClient) GetCert(ctx context.Context, in *GetCertRequest, opts ...grpc.CallOption) (*GetCertResponse, error) {
	out := new(GetCertResponse)
	err := c.cc.Invoke(ctx, "/ca.v1.CAService/GetCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CAServiceServer is the server API for CAService service.
// All implementations must embed UnimplementedCAServiceServer
// for forward compatibility
type CAServiceServer interface {
	GenCert(context.Context, *GenCertRequest) (*GenCertResponse, error)
	GetCert(context.Context, *GetCertRequest) (*GetCertResponse, error)
	mustEmbedUnimplementedCAServiceServer()
}

// UnimplementedCAServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCAServiceServer struct {
}

func (UnimplementedCAServiceServer) GenCert(context.Context, *GenCertRequest) (*GenCertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenCert not implemented")
}
func (UnimplementedCAServiceServer) GetCert(context.Context, *GetCertRequest) (*GetCertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCert not implemented")
}
func (UnimplementedCAServiceServer) mustEmbedUnimplementedCAServiceServer() {}

// UnsafeCAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CAServiceServer will
// result in compilation errors.
type UnsafeCAServiceServer interface {
	mustEmbedUnimplementedCAServiceServer()
}

func RegisterCAServiceServer(s grpc.ServiceRegistrar, srv CAServiceServer) {
	s.RegisterService(&CAService_ServiceDesc, srv)
}

func _CAService_GenCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CAServiceServer).GenCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ca.v1.CAService/GenCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CAServiceServer).GenCert(ctx, req.(*GenCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CAService_GetCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CAServiceServer).GetCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ca.v1.CAService/GetCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CAServiceServer).GetCert(ctx, req.(*GetCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CAService_ServiceDesc is the grpc.ServiceDesc for CAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ca.v1.CAService",
	HandlerType: (*CAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenCert",
			Handler:    _CAService_GenCert_Handler,
		},
		{
			MethodName: "GetCert",
			Handler:    _CAService_GetCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ca/v1/ca.proto",
}
