// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 证书不存在
func IsCertNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Error_CERT_NOT_FOUND.String() && e.Code == 404
}

// 证书不存在
func ErrorCertNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, Error_CERT_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// 参数错误
func IsInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Error_INVALID_PARAMS.String() && e.Code == 400
}

// 参数错误
func ErrorInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(400, Error_INVALID_PARAMS.String(), fmt.Sprintf(format, args...))
}

// 证书生成失败
func IsGenCertErr(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == Error_GEN_CERT_ERR.String() && e.Code == 500
}

// 证书生成失败
func ErrorGenCertErr(format string, args ...interface{}) *errors.Error {
	return errors.New(500, Error_GEN_CERT_ERR.String(), fmt.Sprintf(format, args...))
}
