// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Member struct {
	Username  sql.NullString
	OrgID     sql.NullInt32
	CreatedAt sql.NullTime
}

type Org struct {
	ID               int32
	CreatedAt        sql.NullTime
	Owner            string
	Info             []byte
	OrgName          string
	OrgCode          string
	LegalPersonName  string
	LegalPersonPhone string
}

type Role struct {
	Rolename string
}

type User struct {
	ID        int32
	Username  string
	Nickname  sql.NullString
	Passwd    string
	Email     sql.NullString
	CreatedAt sql.NullTime
	Realname  sql.NullString
	Idcard    sql.NullString
	Phone     string
	Avatar    sql.NullString
	Status    sql.NullString
}

type UserRole struct {
	Username  sql.NullString
	Rolename  sql.NullString
	CreatedAt sql.NullTime
}
