// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// AddMember 企业增加成员
	AddMember(ctx context.Context, arg *AddMemberParams) (int64, error)
	// CreateOrg 创建一个用户
	CreateOrg(ctx context.Context, arg *CreateOrgParams) (int64, error)
	// CreateUser 创建一个用户
	CreateUser(ctx context.Context, arg *CreateUserParams) (int64, error)
	// DeleteMember 删除成员
	DeleteMember(ctx context.Context, username sql.NullString) error
	// DeleteOrgMember 企业移除成员
	DeleteOrgMember(ctx context.Context, arg *DeleteOrgMemberParams) error
	// DeleteRelation 删除某用户的所有角色信息
	DeleteRelation(ctx context.Context, username sql.NullString) error
	// DeleteUserByUsername 根据用户id删除用户
	DeleteUserByID(ctx context.Context, arg *DeleteUserByIDParams) error
	// GetOrgByID 根据组织id获取组织信息
	GetOrgByID(ctx context.Context, id int32) (*Org, error)
	// 查询用户所属企业
	GetOrgOfUser(ctx context.Context, username sql.NullString) (*Org, error)
	// GetRoles 获取用户的角色
	GetRolesByUsername(ctx context.Context, username sql.NullString) ([]sql.NullString, error)
	// GetUserByPhone 根据ID获取用户
	GetUserByID(ctx context.Context, id int32) (*User, error)
	// GetUserByPhone 根据手机号获取用户
	GetUserByPhone(ctx context.Context, phone string) (*User, error)
	// GetUserByUsername 根据用户名获取用户信息
	GetUserByUsername(ctx context.Context, username string) (*User, error)
	// GrantRole 为用户赋予角色
	GrantRole(ctx context.Context, arg *GrantRoleParams) error
	// ListOrgMember 企业查询成员列表
	ListOrgMember(ctx context.Context, arg *ListOrgMemberParams) ([]*ListOrgMemberRow, error)
	// RemoveRole 企业移除成员角色
	RemoveRole(ctx context.Context, username sql.NullString) error
	// UpdateIdentity 更新用户实名信息
	UpdateIdentity(ctx context.Context, arg *UpdateIdentityParams) error
	// UpdateOrg 企业信息更新
	UpdateOrg(ctx context.Context, arg *UpdateOrgParams) error
	// UpdatePasswdByUsername 根据用户名更新密码
	UpdatePasswdByUsername(ctx context.Context, arg *UpdatePasswdByUsernameParams) (int64, error)
	// UpdateUser 用户信息更新
	UpdateUser(ctx context.Context, arg *UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
