// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Class struct {
	ID         int32
	Name       sql.NullString
	Des        []byte
	Status     sql.NullString
	CreatedAt  sql.NullTime
	Creator    sql.NullString
	MaterialID int32
	OrgID      int32
	Tm         sql.NullString
}

type Good struct {
	ID        int32
	Status    sql.NullString
	CreatedAt sql.NullTime
	Creator   sql.NullString
	SerialID  sql.NullInt32
}

type Serial struct {
	ID          int32
	ProductTime sql.NullTime
	Status      sql.NullString
	CreatedAt   sql.NullTime
	Creator     sql.NullString
	ClassID     sql.NullInt32
}
