// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: circ/v1/errors.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	// 创建流转记录失败
	Error_CREATE_CIRC_FAILED Error = 0
	// 流转记录不存在
	Error_CIRC_NOT_FOUND Error = 1
	// 参数错误
	Error_INVALID_PARAMS Error = 2
	// 流转记录已存在
	Error_CIRC_ALREADY_EXIST Error = 3
	// 当前操作者非产品所有者
	Error_NOT_OWNER Error = 4
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "CREATE_CIRC_FAILED",
		1: "CIRC_NOT_FOUND",
		2: "INVALID_PARAMS",
		3: "CIRC_ALREADY_EXIST",
		4: "NOT_OWNER",
	}
	Error_value = map[string]int32{
		"CREATE_CIRC_FAILED": 0,
		"CIRC_NOT_FOUND":     1,
		"INVALID_PARAMS":     2,
		"CIRC_ALREADY_EXIST": 3,
		"NOT_OWNER":          4,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_circ_v1_errors_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_circ_v1_errors_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_circ_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_circ_v1_errors_proto protoreflect.FileDescriptor

var file_circ_v1_errors_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x69, 0x72, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x69, 0x72, 0x63, 0x2e, 0x76, 0x31, 0x1a,
	0x11, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2a, 0x92, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x12,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x49, 0x52, 0x43, 0x5f, 0x46, 0x41, 0x49, 0x4c,
	0x45, 0x44, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0xf4, 0x03, 0x12, 0x18, 0x0a, 0x0e, 0x43, 0x49,
	0x52, 0x43, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x01, 0x1a, 0x04,
	0xa8, 0x45, 0x94, 0x03, 0x12, 0x18, 0x0a, 0x0e, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f,
	0x50, 0x41, 0x52, 0x41, 0x4d, 0x53, 0x10, 0x02, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x12, 0x1c,
	0x0a, 0x12, 0x43, 0x49, 0x52, 0x43, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45,
	0x58, 0x49, 0x53, 0x54, 0x10, 0x03, 0x1a, 0x04, 0xa8, 0x45, 0x90, 0x03, 0x12, 0x13, 0x0a, 0x09,
	0x4e, 0x4f, 0x54, 0x5f, 0x4f, 0x57, 0x4e, 0x45, 0x52, 0x10, 0x04, 0x1a, 0x04, 0xa8, 0x45, 0x90,
	0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x65, 0x65,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x63, 0x69, 0x69, 0x70, 0x2d, 0x69, 0x63, 0x70, 0x2f, 0x76,
	0x2d, 0x74, 0x72, 0x61, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x69, 0x72, 0x63, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_circ_v1_errors_proto_rawDescOnce sync.Once
	file_circ_v1_errors_proto_rawDescData = file_circ_v1_errors_proto_rawDesc
)

func file_circ_v1_errors_proto_rawDescGZIP() []byte {
	file_circ_v1_errors_proto_rawDescOnce.Do(func() {
		file_circ_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_circ_v1_errors_proto_rawDescData)
	})
	return file_circ_v1_errors_proto_rawDescData
}

var file_circ_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_circ_v1_errors_proto_goTypes = []interface{}{
	(Error)(0), // 0: circ.v1.Error
}
var file_circ_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_circ_v1_errors_proto_init() }
func file_circ_v1_errors_proto_init() {
	if File_circ_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_circ_v1_errors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_circ_v1_errors_proto_goTypes,
		DependencyIndexes: file_circ_v1_errors_proto_depIdxs,
		EnumInfos:         file_circ_v1_errors_proto_enumTypes,
	}.Build()
	File_circ_v1_errors_proto = out.File
	file_circ_v1_errors_proto_rawDesc = nil
	file_circ_v1_errors_proto_goTypes = nil
	file_circ_v1_errors_proto_depIdxs = nil
}
