// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"gitee.com/qciip-icp/v-trace/app/circ/internal/biz"
	"gitee.com/qciip-icp/v-trace/app/circ/internal/conf"
	"gitee.com/qciip-icp/v-trace/app/circ/internal/data"
	"gitee.com/qciip-icp/v-trace/app/circ/internal/server"
	"gitee.com/qciip-icp/v-trace/app/circ/internal/service"
	"gitee.com/qciip-icp/v-trace/pkg/app"
	"gitee.com/qciip-icp/v-trace/pkg/registry"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, c *conf.Bootstrap) (*app.App, error) {
	dataConfig := &c.Data
	dataData := data.NewData(ctx, dataConfig)
	circCase := biz.NewCircCase(ctx, dataData)
	circService := service.NewCircService(ctx, circCase)
	grpcServer := server.NewGrpcServer(ctx, c, circService)
	etcd := &c.Etcd
	registryRegistry := registry.NewRegistry(ctx, etcd)
	appApp := newApp(grpcServer, registryRegistry)
	return appApp, nil
}
