// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"gitee.com/qciip-icp/v-trace/app/ca/internal/server"
	"gitee.com/qciip-icp/v-trace/app/ca/internal/service"
	"gitee.com/qciip-icp/v-trace/app/ca/pkg/utils"
	"gitee.com/qciip-icp/v-trace/pkg/app"
	"gitee.com/qciip-icp/v-trace/pkg/registry"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, c *utils.AllConfig) *app.App {
	caService := service.NewCaService()
	grpcServer := server.NewGrpcServer(ctx, caService)
	etcd := &c.Etcd
	registryRegistry := registry.NewRegistry(ctx, etcd)
	appApp := newApp(grpcServer, registryRegistry)
	return appApp
}
