// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"gitee.com/qciip-icp/v-trace/app/trans-job/internal/conf"
	"gitee.com/qciip-icp/v-trace/app/trans-job/internal/job"
	"gitee.com/qciip-icp/v-trace/pkg/cron"
	"gitee.com/qciip-icp/v-trace/pkg/registry"
)

// Injectors from wire.go:

func InitTransJob(ctx context.Context, c *conf.Bootstrap) (cron.JobInterface, error) {
	consumer := NewConsumer(ctx, c)
	redisStore := job.NewCache(ctx, c)
	etcd := &c.Etcd
	registryRegistry := registry.NewRegistry(ctx, etcd)
	v := NewNodes(ctx, c)
	transJob := job.NewTransJob(ctx, c, consumer, redisStore, registryRegistry, v...)
	return transJob, nil
}
