// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// GetAvaiableModel 根据material id获取其可用的模型
	GetAvaiableModel(ctx context.Context, materialID sql.NullInt32) ([]*Model, error)
	GetMaterialByID(ctx context.Context, id int32) (*Material, error)
	// 根据model id和index获取条目
	GetMaterialID(ctx context.Context, arg *GetMaterialIDParams) (sql.NullInt32, error)
	// 根据模型id获取模型数据
	GetModelByID(ctx context.Context, id int32) (*Model, error)
	// 根据模型名获取模型数据
	GetModelByName(ctx context.Context, name sql.NullString) (*Model, error)
	// 根据material获取条目
	GetRelationByMaterial(ctx context.Context, materialID sql.NullInt32) ([]*Relation, error)
	ListMaterials(ctx context.Context) ([]*Material, error)
	ListModels(ctx context.Context) ([]*Model, error)
	// UpdateModelStatus 根据模型名更新模型状态
	UpdateModelStatus(ctx context.Context, arg *UpdateModelStatusParams) error
}

var _ Querier = (*Queries)(nil)
