version: "1.0"
name: pipeline-20230316
displayName: pipeline-20230316
triggers:
  trigger: auto
  pr:
    branches:
      precise:
        - master
stages:
  - name: stage-0d3ecb4e
    displayName: go build
    strategy: fast
    trigger: auto
    executor:
      - shi-jaylan
      - yangchnet
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: "1.18"
        commands:
          - "# 默认使用goproxy.cn"
          - export GOPROXY=https://goproxy.cn
          - "# 输入你的构建命令"
          - make go.build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./_output/platforms/linux/amd64
        caches:
          - /go/pkg/mod
        notify: []
        strategy:
          retry: "0"
